### ISSUE TITLE
Searching on multiple ingredients via Cocktail DB API

### ISSUE THREAD

**Issue by bercohen** [camerican/Help-Desk#12]
Desire for searching for drinks that match multiple ingredients and arranging the interface so that the user first chooses a spirit, then a category.

**Comment by camerican** [comment]
Unfortunately the Cocktail DB API doesn't appear to support searching for drinks that match multiple ingredients at a given time.  Our solution was to make separate API calls for each ingredient, waiting for a second between each call, and then `union`-ing together the results via Ruby's `&` array operator.

Regarding the desired user experience, by naming the search param on our side with square brackets, we convert it to an array and are able to progressively add in new items to search on for each click through the interface, which enables the desired experience.
