### ISSUE TITLE
Google Maps Geolocation from clicks

### ISSUE THREAD

**Issue by ghost** [camerican/Help-Desk#15]
please

**Comment by camerican** [comment]
We're able to access the latitude and logitude from a click on the map via the Google Maps API:

```
google.maps.event.addListener(map, "click", function (e) {
   console.log( 'coords:', e.latLng );
}
```

Reference: [[StackOverflow](http://stackoverflow.com/questions/9247006/get-latitude-and-longitude-on-click-event-from-google-map)]
