### ISSUE TITLE
Are many success callbacks possible?

### ISSUE THREAD

**Issue by Stevendeleon** [camerican/Help-Desk#17]
Question about "success" call for google api

**Comment by camerican** [comment]
In our conversation we discussed how the `jQuery.ajax` function expects only a single callback specified for the `success` key we pass into its object argument.  The good news is we can, from inside that callback, write any code we want including invoking other function calls.

The desired goal was to enable the user to place additional markers on the map and simultaneously write to the database, which we were able to do with an additional AJAX call.
