### ISSUE TITLE
Backend Issue

### ISSUE THREAD

**Issue by Rappole4** [camerican/Help-Desk#6]
NameError in Journeys#show
<p id="notice"><%= notice %></p>

<p>Start:<%= journey.start_address %></p>
<p>End:<%= journey.end_address %></p>

<%= link_to 'Edit', edit_journey_path(@journey) %> |

**Comment by camerican** [comment]
Issue related to strict parameters not referencing the wrong name for the `start_address` and `end_address`.  This was causing the controller to strip out the submitted values and not save them.
